services:
    _defaults:
        autowire: true
        autoconfigure: true

    Heimseiten\ContaoShowCssInListsBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Resources,HeimseitenContaoShowCssInListsBundle.php,ContaoManager}'
